(part "XAL5050-103MEC"
    (packageRef "XAL5050103MEC")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "COILCRAFT")
    (property "Manufacturer_Part_Number" "XAL5050-103MEC")
    (property "Mouser_Part_Number" "994-XAL5050-103MEC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Coilcraft/XAL5050-103MEC?qs=zCSbvcPd3pZ%2FwY1785KGDw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Fixed Inductors 10uH Shld 20% 4.9A 45mOhms AECQ2{0000}")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/XAL5050-103MEC.pdf")
    (property "symbolName1" "XAL5050-103MEC")
)
