(part "ADP7102ARDZ-R7"
    (packageRef "SOIC127P600X175-9N")
    (interface
        (port "1" (symbPinId 1) (portName "VOUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SENSE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN/UVLO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "PG") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP7102ARDZ-R7")
    (property "Mouser_Part_Number" "584-ADP7102ARDZ-R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP7102ARDZ-R7?qs=WIvQP4zGanhyecxhoOTYew%3D%3D")
    (property "Arrow_Part_Number" "ADP7102ARDZ-R7")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/adp7102ardz-r7/analog-devices?region=nac")
    (property "Description" "Linear Voltage Regulators 300mA HV LDO")
    (property "Datasheet_Link" "https://www.arrow.com/en/products/adp7102ardz-r7/analog-devices?region=nac")
    (property "symbolName1" "ADP7102ARDZ-R7")
)
