(part "ADP7182AUJZ-R7"
    (packageRef "SOT95P280X100-5N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "ADJ") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP7182AUJZ-R7")
    (property "Mouser_Part_Number" "584-ADP7182AUJZ-R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP7182AUJZ-R7?qs=J50fqX%2Fl9ipEM%252BbQxVSVcg%3D%3D")
    (property "Arrow_Part_Number" "ADP7182AUJZ-R7")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/adp7182aujz-r7/analog-devices.html?utm_currency=USD&region=nac")
    (property "Description" "Analog Devices ADP7182AUJZ-R7, LDO Regulator, -200mA Adjustable, -1.2  -28 V, +/-1% 5-Pin, TSOT")
    (property "Datasheet_Link" "http://www.analog.com/media/en/technical-documentation/data-sheets/ADP7182.pdf")
    (property "symbolName1" "ADP7182AUJZ-R7")
)
